# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: 5d67a4b4-md-taco
  namespace: 5d67a4b4
spec:
  template:
    spec: {}
