# Source: cluster-api-byoh/templates/machinedeployment.yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: 5d67a4b4-md-taco
  namespace: 5d67a4b4
spec:
  clusterName: 5d67a4b4
  replicas: 3
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        servicemesh: enabled
        taco-egress-gateway: enabled
        taco-ingress-gateway: enabled
        taco-lma: enabled
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: 5d67a4b4-md-taco
      clusterName: 5d67a4b4
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: ByoMachineTemplate
        name: 5d67a4b4-md-taco
      version: v1.22.3
